### ISSUE TITLE
Implement regex matching for Request path segments

### ISSUE THREAD

**Issue by bradleybeddoes** [gotham-rs/gotham#10]
This slipped past 0.1 simply due to the amount of other work that took priority. Is stubbed where the code needs to be added, roughly node.rs#L267.

The implementation here must force segment regex to be anchored to rule out a common class of vulnerability in web applications.

**Comment by ELD** [comment]
What's the intended behavior for this?

Is it something like this?
0. The route is constructed with a named parameter backed by a regular expression
0. The regex is anchored and matched against the request path segment (i.e. "5001" ~= /^[0-9]+$/)
0. The segment is consumed

But in the case of a named regex URL parameter, how do we map that key => value pair? Or do we at all, if I'm understanding this correctly?

**Comment by bradleybeddoes** [comment]
I haven't given regexp concerns much thought yet but essentially:

1. The [`SegmentType` of `Constrained`](https://github.com/gotham-rs/gotham/blob/master/src/router/tree/node.rs#L25) should hold a compiled regex (not String as shown there right now)
2. After that it is really just adding in some plumbing [here](https://github.com/gotham-rs/gotham/blob/master/src/router/tree/node.rs#L267), which I had envisaged basically delegating to [Regex::is_match](https://doc.rust-lang.org/regex/regex/struct.Regex.html#method.is_match)

All of the code for mapping segment name to the value (which matches the regexp) is in place, no need to do anything there I don't believe. Essentially a `Constrained` `SegmentType` is just a fancy `Dynamic` `SegmentType` if you want to follow through how the code works in that scenario.

I'm not seeing the part about consumption did you mean in the Rust sense?

**Comment by ELD** [comment]
Okay, that's how I figured it would work. Didn't realize that you wanted the `SegmentType` to be a compiled regex instead of a string. As it stands now, my fork compiles the regex during the `is_match` method for the tree traversal. That's an easy thing to change.

For now, it's safe to ignore my third question. It's probably just an assumption on my part about how the Router tree works. I haven't quite fully grokked it yet, so I asked a question based on a mistaken assumption.

Most everything is wrapped up on this minus some minor changes. I'll be submitting a PR shortly with this implementation for you guys to review.

Thanks for answering my questions!
