### ISSUE TITLE
Track Tokio reform and consider what refactoring is required for Gotham to work with Tokio 0.2

### ISSUE THREAD

**Issue by smangelsdorf** [gotham-rs/gotham#165]
This **may** involve changing to `tokio-threadpool`, which would likely require that all our types are `Send` (so that incomplete futures can be passed across threads).

https://github.com/tokio-rs/tokio/pull/141

**Comment by ChristophWurst** [comment]
Here's a list of breaking changes I have found in Hyper [0.12.x](https://github.com/hyperium/hyper/commits/0.12.x) so far:

- [ ] All uses of `Handle` now need to be new-tokio `Handle` (https://github.com/hyperium/hyper/commit/603c3e4d2c6ebb3d495a85c4d9a8b36583eff3fc)
- [ ] `Method`, `Request`, `Response`, `StatusCode`,
  `Version`, and `Uri` have been replaced with types from the `http`
  crate. (https://github.com/hyperium/hyper/commit/f0cdf82fd46d2a166bf36ca83cb81a297ed9a17e)
- [ ] The `hyper::header` module is gone for now. (https://github.com/hyperium/hyper/commit/f0cdf82fd46d2a166bf36ca83cb81a297ed9a17e, https://github.com/hyperium/hyper/issues/1463#issuecomment-381866090)
- [ ] Removed `Client::get`, since it needed to construct a `Request<B>`
  with an empty body. Just use `Client::request` instead. (https://github.com/hyperium/hyper/commit/f0cdf82fd46d2a166bf36ca83cb81a297ed9a17e)

I gave it a shot and updated Gotham `master` to hyper `0.12.x`. While adapting to Tokio changes seemed straight forward, the removed `hyper::header` module caused most errors. I've reported this at [the hyper repo](https://github.com/hyperium/hyper/issues/1463#issuecomment-381866090) because I couldn't find any drop-in replacement for the module, the `http` crate's header types work differently than the old hyper ones.

> which would likely require that all our types are Send

I'm also pretty sure this will be necessary. https://github.com/hyperium/hyper/commit/603c3e4d2c6ebb3d495a85c4d9a8b36583eff3fc did it too.

There was also an obvious naming conflict when adding the `http` crate because gotham has a `http` module too. Should we import it with a different name?

**Comment by smangelsdorf** [comment]
> There was also an obvious naming conflict when adding the `http` crate because gotham has a `http` module too. Should we import it with a different name?

That seems like it would be a nuisance, with the number of times we'd have to refer to it by the wrong name. Would be cleaner just to move `gotham::http::*` to another name. Some ideas:

* `gotham::protocol::*`
* `gotham::raw::*`
* `gotham::*` (i.e. just drop the `http` and move the modules up a level)

Thoughts / other suggestions welcome.

**Comment by ChristophWurst** [comment]
Because jumping to both Hyper 0.12 and tokio 0.1 at once gave me tons of compilation errors and was hard to oversee what needs to be changed, I started porting Gotham to tokio 0.1 -- without updating Hyper. I'm not sure if that's possible right now, but it should at least show how the async types in Gotham have to be adjusted. You can find my WIP at https://github.com/gotham-rs/gotham/compare/master...ChristophWurst:refactor/tokio-reform.

Making types and functions `Send` was easy for the most part. However, I'm now stuck at a major issue with the `State` struct because it's neither `Send` nor `Sync`, giving me errors like

> `futures::Future<Item=(state::State, hyper::Response), Error=(state::State, handler::error::HandlerError)>` cannot be sent between threads safely

Now, the easiest approach would be something like wrapping the `HashMap` in `Arc` and `Mutex`, but I'm afraid this will have an impact on performance due to the conservative locking and also borrowing (mutably) from the state wouldn't be possible anymore -- at least the way it is done now.

**Comment by ChristophWurst** [comment]
> gotham::protocol::*

Sounds like a good replacement :+1:

**Comment by smangelsdorf** [comment]
> Making types and functions `Send` was easy for the most part. However, I'm now stuck at a major issue with the `State` struct because it's neither `Send` nor `Sync`

It may just be a matter of reverting the `State` / `StateData` changes in 8e0d2c8f7f02cd84e45069ce5965c7bc874057f0 to add the `Send` bound back in.

**Comment by ChristophWurst** [comment]
Thanks for the tip, @smangelsdorf. I reverted those changes manually because an automated git revert was not possible, unfortunately. Now the only compilation error left is due to hyper 0.11 using `tokio_core` and not `tokio`:
```
error[E0308]: mismatched types
   --> gotham/src/test/mod.rs:180:20
    |
180 |             .build(&Handle::current());
    |                    ^^^^^^^^^^^^^^^^^^ expected struct `tokio_core::reactor::Handle`, found struct `tokio::reactor::Handle`
    |
    = note: expected type `&tokio_core::reactor::Handle`
               found type `&tokio::reactor::Handle`

error: aborting due to previous error

error: Could not compile `gotham`.
```

I guess this is how far I can migrate to `tokio` without changing hyper right now.

**Comment by ChristophWurst** [comment]
> I guess this is how far I can migrate to tokio without changing hyper right now.

I've found one more bug and fixed it in https://github.com/gotham-rs/gotham/commit/8258747bed6b11d732ec5cc79c7c7cfebad9cd58. Now, if you comment out the `test` module, gotham compiles and only those examples that use `tokio_core` seem to fail.

**Comment by whitfin** [comment]
FWIW I am now taking a look at this based on the work done by @ChristophWurst, but will do something similar in splitting up Tokio Reform & Hyper 0.12 (although the latter is now released).

**Comment by whitfin** [comment]
This PR was accepted which migrates (mostly) to Tokio Reform: https://github.com/gotham-rs/gotham/pull/234 

We still need to update to Hyper 0.12 to be able to remove `tokio_core` completely though.
