### ISSUE TITLE
HashMap/Type-Id-less State using HLists

### ISSUE THREAD

**Issue by cramertj** [gotham-rs/gotham#19]
Currently, the application `State` is implemented using a [`HashMap<TypeId, Box<Any + Send>>`](https://github.com/gotham-rs/gotham/blob/master/src/state/mod.rs#L42). This means that accessing any bit of state data requires a `HashMap` lookup, and all bits of state must be stored on the heap.

This can be avoided by keeping an [`HList`](https://github.com/lloydmeta/frunk/blob/master/core/src/hlist.rs) of the state elements (an `HList` of `RefCell<Option<T>>`s). However, this has the downside of requiring each application to declare their own `State` type, probably using a macro like this:

```rust
macro_rules! State {
    $( $repeated: ty ),* => { GothamState(Hlist![$(RefCell<Option<$repeated>>),*]) }
}

// In the application:
type State = State![MyStateBit1, MyStateBit2, MyStateBit3];
```

Pros: avoids `HashMap` lookup, `Box`ing
Cons: forces users to manually declare a `State` type in their application.

What are your thoughts? Is this a change that the Gotham developers would be interested in?

cc @withoutboats, who has discussed this with me in the past in relation to their web framework, [cargonauts](https://github.com/cargonauts-rs/cargonauts).

**Comment by smangelsdorf** [comment]
Thanks for raising HLists as an option here. It's something we talked about during the early stages, but it goes against the goals we had at the time, and some use cases we've found since:

1. Application developers shouldn't have to manually modify a type definition every time they add a Middleware (for example) which requires one or more pieces of StateData;
2. StateData should be added, mutated and removed (i.e. moved out of State) freely as needed. Without this, it's harder to support other APIs that are affine typed, for example our `SessionData<_>` type which takes an owned `self` when the session is discarded;
3. Private types can be used to control the accessibility of StateData;
4. StateData shouldn't need a Default impl, otherwise they'd need `Option<_>` everywhere internally.

We've avoided boxing in a few places using a HList-like structure (MiddlewareChain and PipelineChain), but in this case it's a conscious attempt to reduce friction in app development rather than doubling down on concrete types. If we could achieve the same end with a HList, I'd be all for it, but in particular number 1 and 3 seem prohibitive to me.

**Comment by smangelsdorf** [comment]
I've left this open because I thought of a possible compromise that could solve most of my stated problems while erring on the side of concrete types. In particular we'd lose the "private types to control visibility" use case, since anything using private types would be unusable for apps that wanted to fully specify the state container's type.

I've started to put together my idea in the Rust playground and before finishing I've run into an unconstrained type error that I can't figure my way past (see L137-148):

https://play.rust-lang.org/?gist=bae9cfc3498cbf137c2b2aac9b0fdc10&version=stable

The basic idea here is:

* A state container would be mostly described by what **can** be put in it, via the `StateContainerWith<T>` trait, so anything fulfilling `StateContainerWith<MyStateData>` would allow `put` / `borrow` / `borrow_mut` / `take` operations for the `MyStateData` as we have today
* The current `State` container could implement this for all `T: StateData`, which would allow it to be the default for apps that wanted the easy / ergonomic experience out of the box (my first point above)
* For applications that wanted to squeeze more performance out, by avoiding boxing and hashmap lookups, we allow a HList-style structure (in the playground code above, I've stuck with what we've used internally in Gotham - a HList built from nested tuples with `()` marking the end)

If this idea can be made to work, then we'd need the `State` type to be parameterised on the `Middleware` and `Handler` traits, with all the necessary flow-on effects from there. I've not investigated yet to see if that's going to be problematic.

An alternate idea that I've had is having the macro (to use your syntax @cramertj):

```rust
type State = State![MyStateBit1, MyStateBit2, MyStateBit3];
```

Expand to something like:

```rust
type State = (Option<MyStateBit1>, (Option<MyStateBit2>, (Option<MyStateBit3>, ())));

impl StateContainerWith<MyStateBit1> for State {
    // Implement everything with `self.0`
}

impl StateContainerWith<MyStateBit2> for State {
    // Implement everything with `self.1.0`
}

impl StateContainerWith<MyStateBit3> for State {
    // Implement everything with `self.1.1.0`
}
```

At a glance this seems a little tricky with macros as they exist today, but it might be doable with some type-level stuff to augment it. Alternately, maybe a custom derive.

Open to any thoughts here, but preferably any tips on how to get further with my "unconstrained type parameter" error. Otherwise I'll continue to tinker with this when I have more time.

**Comment by msrd0** [comment]
Is there a particular reason for trying to avoid using `HashMap` and `Box`? If this is just about avoiding heap usage, I don't think it warrants the overhead and inconvenience of declaring your own state type that has to include types for every middleware used etc.

**Comment by msrd0** [comment]
I'm going to close this due to inactivity
