### ISSUE TITLE
Benchmarks ?

### ISSUE THREAD

**Issue by 0freeman00** [gotham-rs/gotham#27]
hello, thanks for an awesome lib, I was waiting for async HTTP framework since a long time. if possible can you just give benchmarks, so we kinda have some idea? 

Thanks, team.

**Comment by smangelsdorf** [comment]
Thanks for the interest in Gotham, and we certainly look forward to any feedback you'd like to give about the framework.

We regularly benchmark our own changes to ensure we're not unduly introducing a performance regression. The numbers are very dependent on the benchmark implementation and the hardware it runs on, so we have decided to keep them just for local testing.

We've not measured Gotham against other frameworks, so we can't offer a comparison. In the longer term we'd like to enter Gotham into the [TechEmpower benchmarks](https://www.techempower.com/benchmarks/) to get an unbiased comparison that we can reference.

Of course, we're happy for people to measure and compare different frameworks' performance and suitability for their own use cases.

We're also more than happy to hear about any potential optimisations we could make, since we'd love to address them.

**Comment by h2oman256** [comment]
I did some super quick testing of Iron, Gotham, Rocket. Rails and ExpressJS are also included here for reference. The test was basically just a hello world test. I used each of the projects' hello world example code. Testing was done with the [wrk](https://github.com/wg/wrk) program on Ubuntu 16.04 with a Ryzen 1700x and 2666mhz RAM.

Here were the results:

## Gotham
Server command: `~/gotham/example-app $ cargo run --release`
```
Running 10s test @ http://localhost:7878/
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   150.87us   34.12us   1.31ms   71.01%
    Req/Sec    33.02k     2.31k   37.25k    78.22%
  663660 requests in 10.10s, 214.56MB read
Requests/sec:  65712.24
Transfer/sec:     21.24MB
```

## Iron
Server command: `cargo run --release --example simple_routing`
(Note: I used the simple_routing example, otherwise no routing code gets tested, unlike the other frameworks. Instead of benchmarking the index the `/hello` route was used.)
```
Running 10s test @ http://localhost:3000/hello
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    37.69us   44.89us   6.10ms   99.82%
    Req/Sec   122.09k     5.49k  134.70k    66.83%
  2453708 requests in 10.10s, 269.10MB read
Requests/sec: 242950.24
Transfer/sec:     26.64MB
```

## Rocket
Server command: `~/rocket/examples/hello_world $ cargo run --release`
```
Running 10s test @ http://localhost:8000/
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   326.11us  247.32us   6.35ms   78.92%
    Req/Sec    16.47k   711.93    17.53k    69.31%
  330897 requests in 10.10s, 46.07MB read
Requests/sec:  32763.10
Transfer/sec:      4.56MB
```


## Rails
Server command: `RAILS_ENV=production rails s`
```
Running 10s test @ http://localhost:3000/
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.42ms  709.15us  21.33ms   80.04%
    Req/Sec     1.77k   385.37     2.42k    55.50%
  35309 requests in 10.00s, 4.55MB read
  Non-2xx or 3xx responses: 35309
Requests/sec:   3530.28
Transfer/sec:    465.42KB
```

## ExpressJS
Server command: `NODE_ENV=prod npm start`
```
Running 10s test @ http://localhost:3000/
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.26ms  678.74us  23.76ms   95.57%
    Req/Sec     4.08k   594.55     4.43k    91.00%
  81141 requests in 10.00s, 16.64MB read
Requests/sec:   8113.85
Transfer/sec:      1.66MB
```

**Comment by 0freeman00** [comment]
woow, how is iron so fast ??? awesome, i thought `iron` is out of game. ;)

**Comment by bradleybeddoes** [comment]
@h2oman256 interesting numbers, thanks for the effort to collate these. 👍 

@0freeman00 this can be the problem with benchmarks and why we've not explored them yet. It is hard to really tell how "real world" any outcome is, was this really a level playing field etc. The level playing field is one aspect of the [TechEmpower benchmarks](https://www.techempower.com/benchmarks/) that is quite attractive to us in the longer term.

That disclaimer aside, I am glad to see Gotham did quite well here. Getting some understanding as to why `Iron` is so far out in front would be useful. Seeing increases for threads/connections would be interesting given `Iron` is not async (to the best of my knowledge).

**Comment by xilec** [comment]
@h2oman256 I suppose, rocket should be much faster if run it in production mode (environment variable: `ROCKET_ENV=prod`).
According to [this issue](https://github.com/SergioBenitez/Rocket/issues/315) rocket, iron and nickel have the same level of performance.

**Comment by smangelsdorf** [comment]
Interesting results all around, thanks for sharing @h2oman256, and thanks to others for the comments.

We're quite close to the performance of raw hyper/tokio. On a work-in-progress branch I have which boosts our performance a little, I'm only seeing about an 18% performance drop going from hyper's "Hello, world!" to a Gotham equivalent.

As Gotham matures, we'll spend more effort understanding what is happening in Iron or Rocket that makes them so much faster in micro-benchmarks like this. I'm also keen to see how Gotham compares once we see some completely async apps being written against a database and being hit with a large amount of concurrency.

**Comment by crusty-dave** [comment]
Any idea when you will get the [TechEmpower benchmarks](https://www.techempower.com/benchmarks/#section=test&runid=d06ed950-3314-47f0-8708-137a9378ffe7) running?  I would be curious to see how gotham compares to actix-web.  It may be a moot point, I have a project that really needs native TLS, depending on how much longer that takes to get to stable, it may be too late.

**Comment by whitfin** [comment]
@crusty-dave personally, I see no use of the other benchmarks as they’re gauging things outside of the framework (e.g. database throughput). IMO the plain text one is sufficient to compare.

That being said, if you want to PR those benchmarks, I’m happy to assist as needed!
