### ISSUE TITLE
Is this still active and cleanup of issues

### ISSUE THREAD

**Issue by Darksonn** [gotham-rs/gotham#341]
I am trying to choose a library for a web server and was evaluating how active this project is.
I see that there are somewhat recent commits, so it doesn't seem abandoned, but is there still active development, or is it mostly occasional bug-fixes? (or maybe everyone is just on vacation)

I also notice that there are a lot of very old open issues. According to the insights page, they are all more than a month old. I think you should [consider closing][1] some of the old issues.

[1]: https://blog.jessfraz.com/post/the-art-of-closing/

**Comment by mkaito** [comment]
They literally just released a new version a few weeks ago :wink:

**Comment by Darksonn** [comment]
Ah! I didn't even notice, I was just looking at commits.

**Comment by whitfin** [comment]
Hi @Darksonn!

Yes there is active development, but you should know that it's not that everybody is on vacation. None of the maintainers work on Gotham as their day job; it is contribution done in free time. So naturally the flow of work will vary periodically. We encourage others to get involved if there's something they want to see added! 

In terms of the issues, the ones remaining have largely survived several cleanup passes and are generally still valid and should remain open (the link you provided appears to be talking more about closing PRs rather than issues themselves?). We do run over them from time to time just to check that nothing has already been resolved/invalidated. 

If you have any other questions just let me know!

**Comment by Darksonn** [comment]
Thank you! I do really like the design choices of gotham, so I'm excited to hear that it is still actively developed.
