### ISSUE TITLE
Simplify use statements with re-exports

### ISSUE THREAD

**Issue by IntrepidPig** [gotham-rs/gotham#71]
Right now, gotham is structured with a relatively deep tree. This leads to lots of large `use` statements in certain files, for example, the [routing file in the example app](https://github.com/gotham-rs/example-app/blob/master/src/boot/router.rs). These statements can be simplified by reexporting types deeper in the tree from higher level modules.

In case I'm not explaining it properly, I mean being able to convert this:
```rust
use gotham::router::request::path::NoopPathExtractor;
use gotham::router::request::query_string::NoopQueryStringExtractor;
use gotham::router::tree::TreeBuilder;
use gotham::router::tree::node::{NodeBuilder, SegmentType};
```
to something like
```rust
use gotham::router::request::{NoopPathExtractor, NoopQueryStringExtractor};
use gotham::router::tree::{TreeBuilder, NodeBuilder, SegmentType};
```

I think this could also be done with other crates like hyper and mime to provide a more streamlined experience, but that might be too much.

**Comment by bradleybeddoes** [comment]
I'm certainly keen to see this happen, I guess the thought was to leave this until after 0.1 (possibly 0.2?) so that folks aren't impacted by structure that could be in flux as they upgrade releases.

However as we've seen in https://github.com/gotham-rs/gotham/pull/70 folks seem comfortable with this kind of thing.

@smangelsdorf I'm happy to progress this if you're onboard.

**Comment by smangelsdorf** [comment]
Sounds good.

**Comment by smangelsdorf** [comment]
Reopening. That PR wasn't a complete fix.
