### ISSUE TITLE
Add example that shows usage of Diesel middleware

### ISSUE THREAD

**Issue by bradleybeddoes** [gotham-rs/gotham#77]

**Comment by n-pochet** [comment]
Hi,
I discovered recently your project and I think it is really nice.
I really would like to help. 
Because for one of my project I would need to use the Diesel middleware, I would like to help on this issue.
For the moment, I'm still in the process of learning Gotham and trying to understand how to use all the components (especially middlewares and pipelines).
For the example app, I thought about making a simple app that would be able to retrieve some fields in the DB in reaction to a GET request. That app would serve some posts (like in the Getting started app of Diesel [Diesel Getting Started](http://diesel.rs/guides/getting-started/)) but using SQlite instead of Postgres.
Ideally, it would be nice to have all the CRUD operations implemented.
What do you think?
Any advice regarding the code organization? The basic example of Diesel provides some modules and a main `lib.rs` file.
Thank you beforehand for the help!
Kind regards,

Nicolas

**Comment by bradleybeddoes** [comment]
Hi @n-pochet welcome to the Gotham project and thank you for your kind words.

I see you've submitted PR #126 which is awesome, I'll make some comments and work with you on this over there, might be a day or so until I get to do that, very busy weekend on this side 👍.

**Comment by msrd0** [comment]
I believe this has been done in #313
